// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calservice.proto

package autogenerated;

public interface ExactBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExactBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BookRequest book = 1;</code>
   */
  boolean hasBook();
  /**
   * <code>.BookRequest book = 1;</code>
   */
  BookRequest getBook();
  /**
   * <code>.BookRequest book = 1;</code>
   */
  BookRequestOrBuilder getBookOrBuilder();
}
