// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calservice.proto

package autogenerated;

public interface SelectBookByNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SelectBookByNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
