// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calservice.proto

package autogenerated;

/**
 * Protobuf type {@code VagueBookResponse}
 */
public  final class VagueBookResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VagueBookResponse)
    VagueBookResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VagueBookResponse.newBuilder() to construct.
  private VagueBookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VagueBookResponse() {
    bookList_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VagueBookResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              bookList_ = new java.util.ArrayList<BookRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            bookList_.add(
                input.readMessage(BookRequest.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        bookList_ = java.util.Collections.unmodifiableList(bookList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Calservice.internal_static_VagueBookResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Calservice.internal_static_VagueBookResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VagueBookResponse.class, Builder.class);
  }

  public static final int BOOKLIST_FIELD_NUMBER = 1;
  private java.util.List<BookRequest> bookList_;
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  public java.util.List<BookRequest> getBookListList() {
    return bookList_;
  }
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  public java.util.List<? extends BookRequestOrBuilder>
      getBookListOrBuilderList() {
    return bookList_;
  }
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  public int getBookListCount() {
    return bookList_.size();
  }
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  public BookRequest getBookList(int index) {
    return bookList_.get(index);
  }
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  public BookRequestOrBuilder getBookListOrBuilder(
      int index) {
    return bookList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bookList_.size(); i++) {
      output.writeMessage(1, bookList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bookList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, bookList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VagueBookResponse)) {
      return super.equals(obj);
    }
    VagueBookResponse other = (VagueBookResponse) obj;

    boolean result = true;
    result = result && getBookListList()
        .equals(other.getBookListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBookListCount() > 0) {
      hash = (37 * hash) + BOOKLIST_FIELD_NUMBER;
      hash = (53 * hash) + getBookListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VagueBookResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VagueBookResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VagueBookResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VagueBookResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VagueBookResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VagueBookResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VagueBookResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VagueBookResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VagueBookResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VagueBookResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VagueBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VagueBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VagueBookResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VagueBookResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VagueBookResponse)
      VagueBookResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Calservice.internal_static_VagueBookResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Calservice.internal_static_VagueBookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VagueBookResponse.class, Builder.class);
    }

    // Construct using autogenerated.VagueBookResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBookListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (bookListBuilder_ == null) {
        bookList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        bookListBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Calservice.internal_static_VagueBookResponse_descriptor;
    }

    public VagueBookResponse getDefaultInstanceForType() {
      return VagueBookResponse.getDefaultInstance();
    }

    public VagueBookResponse build() {
      VagueBookResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public VagueBookResponse buildPartial() {
      VagueBookResponse result = new VagueBookResponse(this);
      int from_bitField0_ = bitField0_;
      if (bookListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          bookList_ = java.util.Collections.unmodifiableList(bookList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bookList_ = bookList_;
      } else {
        result.bookList_ = bookListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VagueBookResponse) {
        return mergeFrom((VagueBookResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VagueBookResponse other) {
      if (other == VagueBookResponse.getDefaultInstance()) return this;
      if (bookListBuilder_ == null) {
        if (!other.bookList_.isEmpty()) {
          if (bookList_.isEmpty()) {
            bookList_ = other.bookList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBookListIsMutable();
            bookList_.addAll(other.bookList_);
          }
          onChanged();
        }
      } else {
        if (!other.bookList_.isEmpty()) {
          if (bookListBuilder_.isEmpty()) {
            bookListBuilder_.dispose();
            bookListBuilder_ = null;
            bookList_ = other.bookList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bookListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBookListFieldBuilder() : null;
          } else {
            bookListBuilder_.addAllMessages(other.bookList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VagueBookResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VagueBookResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<BookRequest> bookList_ =
      java.util.Collections.emptyList();
    private void ensureBookListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        bookList_ = new java.util.ArrayList<BookRequest>(bookList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        BookRequest, BookRequest.Builder, BookRequestOrBuilder> bookListBuilder_;

    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public java.util.List<BookRequest> getBookListList() {
      if (bookListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bookList_);
      } else {
        return bookListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public int getBookListCount() {
      if (bookListBuilder_ == null) {
        return bookList_.size();
      } else {
        return bookListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public BookRequest getBookList(int index) {
      if (bookListBuilder_ == null) {
        return bookList_.get(index);
      } else {
        return bookListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder setBookList(
        int index, BookRequest value) {
      if (bookListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookListIsMutable();
        bookList_.set(index, value);
        onChanged();
      } else {
        bookListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder setBookList(
        int index, BookRequest.Builder builderForValue) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.set(index, builderForValue.build());
        onChanged();
      } else {
        bookListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder addBookList(BookRequest value) {
      if (bookListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookListIsMutable();
        bookList_.add(value);
        onChanged();
      } else {
        bookListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder addBookList(
        int index, BookRequest value) {
      if (bookListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookListIsMutable();
        bookList_.add(index, value);
        onChanged();
      } else {
        bookListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder addBookList(
        BookRequest.Builder builderForValue) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.add(builderForValue.build());
        onChanged();
      } else {
        bookListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder addBookList(
        int index, BookRequest.Builder builderForValue) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.add(index, builderForValue.build());
        onChanged();
      } else {
        bookListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder addAllBookList(
        Iterable<? extends BookRequest> values) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bookList_);
        onChanged();
      } else {
        bookListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder clearBookList() {
      if (bookListBuilder_ == null) {
        bookList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bookListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public Builder removeBookList(int index) {
      if (bookListBuilder_ == null) {
        ensureBookListIsMutable();
        bookList_.remove(index);
        onChanged();
      } else {
        bookListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public BookRequest.Builder getBookListBuilder(
        int index) {
      return getBookListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public BookRequestOrBuilder getBookListOrBuilder(
        int index) {
      if (bookListBuilder_ == null) {
        return bookList_.get(index);  } else {
        return bookListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public java.util.List<? extends BookRequestOrBuilder>
         getBookListOrBuilderList() {
      if (bookListBuilder_ != null) {
        return bookListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bookList_);
      }
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public BookRequest.Builder addBookListBuilder() {
      return getBookListFieldBuilder().addBuilder(
          BookRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public BookRequest.Builder addBookListBuilder(
        int index) {
      return getBookListFieldBuilder().addBuilder(
          index, BookRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .BookRequest bookList = 1;</code>
     */
    public java.util.List<BookRequest.Builder>
         getBookListBuilderList() {
      return getBookListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        BookRequest, BookRequest.Builder, BookRequestOrBuilder>
        getBookListFieldBuilder() {
      if (bookListBuilder_ == null) {
        bookListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            BookRequest, BookRequest.Builder, BookRequestOrBuilder>(
                bookList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        bookList_ = null;
      }
      return bookListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VagueBookResponse)
  }

  // @@protoc_insertion_point(class_scope:VagueBookResponse)
  private static final VagueBookResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VagueBookResponse();
  }

  public static VagueBookResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VagueBookResponse>
      PARSER = new com.google.protobuf.AbstractParser<VagueBookResponse>() {
    public VagueBookResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VagueBookResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VagueBookResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VagueBookResponse> getParserForType() {
    return PARSER;
  }

  public VagueBookResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

