// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calservice.proto

package autogenerated;

public interface VagueBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VagueBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  java.util.List<BookRequest>
      getBookListList();
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  BookRequest getBookList(int index);
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  int getBookListCount();
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  java.util.List<? extends BookRequestOrBuilder>
      getBookListOrBuilderList();
  /**
   * <code>repeated .BookRequest bookList = 1;</code>
   */
  BookRequestOrBuilder getBookListOrBuilder(
      int index);
}
